fail_fast: true
repos:
  # Formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1 # or master
    hooks:
      - id: black

  # Pre commit checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # or master
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]

      ### Conflicts
      - id: check-case-conflict

      ### File type check
      - id: check-json
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml

      # Formatting
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]

  # Commit messages checks
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      # - id: commitizen-branch # ensure the entire branch follows this convention
