fail_fast: true
repos:

  ### Formatter and Linter (Flake8 + Black replacement)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.6
    hooks:
      # Run the linter.
      - id: ruff
        # types_or: [ python, pyi, jupyter ] # Add for Jupyter
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        # types_or: [ python, pyi, jupyter ] # Add for Jupyter

  # Pre commit checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # or master
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]

      ### Conflicts
      - id: check-case-conflict

      ### File type check
      - id: check-json
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml

      # Formatting
      # - id: double-quote-string-fixer # DOES NOT WORK WITH BLACK
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]

  # Commit messages checks
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      # - id: commitizen-branch # ensure the entire branch follows this convention
